version: "3.8"

services:
  sdk:
    build:
        context: containers/nixdev
        dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/workspace/
      - ./home/:/home/main/
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/run/user/1000/wayland-0
    network_mode: host
    devices:
      - /dev/dri
    group_add:
      - video
    security_opt:
      - label:seccomp:unconfined
